server:
  port: 9002

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa_ecommerce
    username: msa
    password: msa1234
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: catalog-service-group
      auto-offset-reset: earliest

app:
  init-data:
    enabled: true
  kafka:
    catalog-topic: example-catalog-topic

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.catalogservice: DEBUG
