server:
  port: 9002
spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/msa_ecommerce}
    username: ${DB_USERNAME:msa}
    password: ${DB_PASSWORD:msa1234}
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: catalog-service-group
      auto-offset-reset: earliest
app:
  init-data:
    enabled: true
  kafka:
    catalog-topic: example-catalog-topic

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:127.0.0.1}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8761/eureka}

logging:
  level:
    com.example.catalogservice: DEBUG
