input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "[@metadata][target_index]" => "msa-market-logs-%{+YYYY.MM.dd}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
    ilm_enabled => false
  }

  stdout {
    codec => rubydebug
  }
}
