server:
  port: 9001

spring:
  application:
    name: user-service
  cloud:
    bus:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa_ecommerce
    username: msa
    password: msa1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

gateway:
  ip: 127.0.0.1

token:
  expiration_time: 86400000
  secret: msa_test_token_secret_2026

greeting:
  message: Welcome to the Simple E-commerce.

app:
  init-data:
    enabled: true

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus
